name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Build artifacts
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-app-artifact
        path: ./publish

    - name: Run tests excluding PerformanceTest
      run: |
        dotnet test --no-build --filter "FullyQualifiedName!~TourGuideTest.PerformanceTest.HighVolumeTrackLocation&FullyQualifiedName!~TourGuideTest.PerformanceTest.HighVolumeGetRewards" --verbosity normal
